apiVersion: apps/v1
kind: Deployment
metadata:
  name: KakaoAPI
  labels:
    app: KakaoAPI
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KakaoAPI
  template:
    metadata:
      labels:
        app: KakaoAPI
    spec:
      containers:
        - name: KakaoAPI
          image: username/KakaoAPI:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5