apiVersion: apps/v1
kind: Deployment
metadata:
  name: CleanerRegistration
  labels:
    app: CleanerRegistration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CleanerRegistration
  template:
    metadata:
      labels:
        app: CleanerRegistration
    spec:
      containers:
        - name: CleanerRegistration
          image: username/CleanerRegistration:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5