apiVersion: v1
kind: Service
metadata:
  name: CleanerRegistration
  labels:
    app: CleanerRegistration
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CleanerRegistration